#!/bin/sh

userresources=$XDG_CONFIG_HOME/x11/Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

[[ -f ~/.zshenv ]] && source ~/.zshenv

setxkbmap -option caps:swapescape &
xset r rate 300 50 &
xbindkeys -p -f /home/victor/.config/xbindkeys/config/xbindkeysrc &
nitrogen --restore &
exec wal -R &
exec xautolock -time 10 -corners -000 -locker slock &
exec picom &
exec xmonad
